---
- name: "Updating the guest operating system."
  ansible.builtin.dnf:
    name: "*"
    state: latest     # noqa package-latest
    update_cache: "yes"
- name: Add Additional Packages
  ansible.builtin.dnf:
    name:
      - wget
      - net-tools
      - unzip
      - ca-certificates
      - amazon-efs-utils
    state: present
