---
- name: "Updating the guest operating system."
  ansible.builtin.dnf:
    name: "*"
    state: latest     # noqa package-latest
    update_cache: "yes"
- name: Add K3S-SELinux Package RPM Keys
  ansible.builtin.rpm_key:
    key: '{{ item }}'
    state: present
  loop:
    - https://rpm.rancher.io/public.key
    - https://rpm-testing.rancher.io/public.key
- name: Add Additional Packages
  ansible.builtin.dnf:
    name:
      - wget
      - net-tools
      - unzip
      - ca-certificates
      - amazon-efs-utils
      - python3-pip
      - container-selinux
      - iptables-nft
      - https://github.com/k3s-io/k3s-selinux/releases/download/v1.5.stable.1/k3s-selinux-1.5-1.el8.noarch.rpm
    state: present
- name: Add /usr/local/bin to sudo secure_path
  ansible.builtin.lineinfile:
    line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
    regexp: "Defaults(\\s)*secure_path(\\s)*="
    state: present
    insertafter: EOF
    path: /etc/sudoers
    validate: 'visudo -cf %s'
- name: Add br_netfilter to /etc/modules-load.d/
  ansible.builtin.copy:
    content: "br_netfilter"
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: "u=rw,g=,o="

- name: Load br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Set bridge-nf-call-iptables (just to be sure)
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: true
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Add Cloudflare Repo
  ansible.builtin.yum_repository:
    name: cloudflared-stable
    description: Cloudflared Stable
    baseurl: https://pkg.cloudflare.com/cloudflared/rpm
    enabled: true
    gpgcheck: true
    gpgkey: https://pkg.cloudflare.com/cloudflare-ascii-pubkey.gpg

- name: Install Cloudflared Repo Key
  ansible.builtin.rpm_key:
    key: https://pkg.cloudflare.com/cloudflare-ascii-pubkey.gpg
    state: present

- name: Add Tailscale repository
  ansible.builtin.yum_repository:
    name: tailscale
    description: Tailscale
    baseurl: https://pkgs.tailscale.com/stable/rhel/8/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://pkgs.tailscale.com/stable/rhel/8/repo.gpg

- name: Install Tailscale Repo Key
  ansible.builtin.rpm_key:
    key: https://pkgs.tailscale.com/stable/rhel/8/repo.gpg
    state: present

- name: Install Tailscale Package
  ansible.builtin.dnf:
    name: tailscale
    state: present

- name: Disable Tailscale Service on AMI
  ansible.builtin.service:
    name: tailscaled
    enabled: false
    state: stopped
