---
- name: Register System with RHSM
  community.general.redhat_subscription:
    state: present
    username: '{{ rhsm_username }}'
    password: '{{ rhsm_password }}'
    pool_ids:
      - '{{ rhsm_pool_id }}'
  when:
    - "ansible_facts['distribution'] == 'RedHat'"
- name: Refresh Subscription Manager when Online
  ansible.builtin.shell: "subscription-manager refresh"
  when:
    - "ansible_facts['distribution'] == 'RedHat'"
- name: "Updating the guest operating system."
  ansible.builtin.dnf:
    name: "*"
    state: latest     # noqa package-latest
    update_cache: "yes"
  when: "ansible_facts['distribution_major_version'] >= \"8\""
- name: Add Additional Packages
  ansible.builtin.dnf:
    name:
      - wget
      - curl
      - net-tools
      - unzip
      - ca-certificates
      - python3-pip
    state: present
- name: Download EFS Utils Package
  ansible.builtin.get_url:
    url: "https://{{ s3_bucket }}.s3.{{ s3_region }}.amazonaws.com/{{ efs_utils_package }}"
    dest: "/root"
    checksum: '{{ efs_utils_checksum }}'
    mode: '0644'
  when:
    s3_source
- name: Install EFS Utils Package
  ansible.builtin.dnf:
    name: "/root/{{ efs_utils_package }}"
    state: present
