---
- name: Register System with RHSM
  community.general.redhat_subscription:
    state: present
    username: '{{ rhsm_username }}'
    password: '{{ rhsm_password }}'
    pool_ids:
      - '{{ rhsm_pool_id }}'
  when:
    - "ansible_facts['distribution'] == 'RedHat'"
- name: Refresh Subscription Manager when Online
  ansible.builtin.shell: "subscription-manager refresh"
  when:
    - "ansible_facts['distribution'] == 'RedHat'"
- name: "Updating the guest operating system."
  ansible.builtin.dnf:
    name: "*"
    state: latest     # noqa package-latest
    update_cache: "yes"
  when: "ansible_facts['distribution_major_version'] >= \"8\""
- name: Add Additional Packages
  ansible.builtin.dnf:
    name:
      - wget
      - curl
      - net-tools
      - unzip
      - ca-certificates
      - python3-pip
      - container-selinux
      - https://github.com/k3s-io/k3s-selinux/releases/download/v1.5.stable.1/k3s-selinux-1.5-1.el8.noarch.rpm
    state: present
- name: Install AWS CLI Package
  ansible.builtin.pip:
    name: 
      - awscli
      - boto3
      - botocore
- name: Download EFS Utils Package
  amazon.aws.s3_object:
    region: '{{ s3_region }}'
    bucket: '{{ s3_bucket }}'
    object: '{{ efs_utils_rpm_package }}'
    dest: "/root/{{ efs_utils_rpm_package }}"
    mode: get
  when:
    s3_source
- name: Install EFS Utils Package
  ansible.builtin.dnf:
    name: "/root/{{ efs_utils_rpm_package }}"
    disable_gpg_check: true
    state: present
- name: Add /usr/local/bin to sudo secure_path
  ansible.builtin.lineinfile:
    line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
    regexp: "Defaults(\\s)*secure_path(\\s)*="
    state: present
    insertafter: EOF
    path: /etc/sudoers
    validate: 'visudo -cf %s'
- name: Add br_netfilter to /etc/modules-load.d/
  ansible.builtin.copy:
    content: "br_netfilter"
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: "u=rw,g=,o="

- name: Load br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Set bridge-nf-call-iptables (just to be sure)
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: true
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Download FIPS Cloudflare Tunnel Package
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cloudflared/releases/download/2023.10.0/cloudflared-fips-linux-x86_64.rpm
    timeout: 120
    dest: /tmp/cloudflared.rpm
    owner: root
    group: root
    mode: 0644
    checksum: sha256:d79111ec8fa3659c887dd4e82f8ce6ff39391de6860ca0c2045469d6ab76a44f

- name: Add Tailscale repository
  ansible.builtin.yum_repository:
    name: tailscale
    description: Tailscale
    baseurl: https://pkgs.tailscale.com/stable/rhel/8/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: https://pkgs.tailscale.com/stable/rhel/8/repo.gpg

- name: Install Tailscale Repo Key
  ansible.builtin.rpm_key:
    key: https://pkgs.tailscale.com/stable/rhel/8/repo.gpg
    state: present

- name: Install Tailscale Package
  ansible.builtin.dnf:
    name: tailscale
    state: present

- name: Disable Tailscale Service on AMI
  ansible.builtin.service:
    name: tailscaled
    enabled: false
    state: stopped