---
- name: Update the guest operating system
  ansible.builtin.apt:
    force_apt_get: true
    name: "*"
    state: latest
    update_cache: true
- name: Add Additional Required Packages
  ansible.builtin.apt:
    pkg:
      - wget
      - curl
      - amazon-efs-utils
      - iptables
- name: Install Dependent Ubuntu Packages
  when: ansible_distribution in ['Ubuntu']
  ansible.builtin.apt:
    name: policycoreutils  # Used by install script to restore SELinux context
    update_cache: yes
