---
- name: Update the guest operating system
  ansible.builtin.apt:
    force_apt_get: true
    name: "*"
    state: latest
    update_cache: true
- name: Add Additional Required Packages
  ansible.builtin.apt:
    pkg:
      - wget
      - curl
      - amazon-efs-utils
      - iptables
- name: Install Dependent Ubuntu Packages
  when: ansible_distribution in ['Ubuntu']
  ansible.builtin.apt:
    name: policycoreutils  # Used by install script to restore SELinux context
    update_cache: yes

- name: Download FIPS Cloudflare Tunnel Package
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cloudflared/releases/download/2023.10.0/cloudflared-fips-linux-amd64.deb
    timeout: 120
    dest: /tmp/cloudflared.deb
    owner: root
    group: root
    mode: 0644
    checksum: sha256:569b8925a41bd1426fc9f88a4d00aa93da747ed4a5ec1c638678ac62ae1a7114
